[package]
name = "sudoko"
version = "0.5.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.1.0"
console = "0.15.8"
clearscreen = "3.0.0"
itertools = "0.13.0"